page_params:
  title: The Team
  description: "Meet the team behind the mkdocs-authors-plugin."
  avatar_shape: circle
  avatar_size: 150
  avatar_align: left

authors:
  author_one:
    name: Thomas Zwagerman
    description: Owner & Maintainer
    avatar: https://avatars.githubusercontent.com/u/36264706?v=4
    affiliation: British Antarctic Survey
    email: thozwa@bas.ac.uk
    github: thomaszwagerman
    linkedin: thomaszwagerman
    twitter: thomzwa
  author_two:
    name: Zhomas Twagerman
    description: Definitely not Thomas Zwagerman
    avatar: /images/imposter.png
    affiliation: British Antarctic Survey