authors:
  author_one:
    name: Thomas Zwagerman
    description: Owner
    avatar: https://avatars.githubusercontent.com/u/36264706?v=4
    affiliation: British Antarctic Survey
    email: thozwa@bas.ac.uk
    github: thomaszwagerman
    linkedin: thomaszwagerman
    twitter: thomaszwagerman
  author_two:
    name: Thomas Zwagerman
    description: Owner
    avatar: https://avatars.githubusercontent.com/u/36264706?v=4
    affiliation: British Antarctic Survey
    email: thozwa@bas.ac.uk
    github: thomaszwagerman
    linkedin: thomaszwagerman
    twitter: thomaszwagerman