page_params:
  title: The Team
  description: "Meet the team behind the mkdocs-authors-plugin."
  avatar_shape: circle
  avatar_size: 150
  avatar_align: left

authors:
  author_one:
    name: Thomas Zwagerman
    description: Owner & Maintainer
    avatar: https://avatars.githubusercontent.com/u/36264706?v=4
    affiliation: British Antarctic Survey
    email: thozwa@bas.ac.uk
    github: thomaszwagerman
    linkedin: thomaszwagerman
    orcid: 0009-0003-3742-3234
  author_two:
    name: Giuseppe
    description: Project Supervisor
    avatar: ../images/giuseppe.jpeg