# mkdocs-authors-plugin/.github/workflows/deploy-docs.yml
name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install MkDocs and Material theme
      run: |
        pip install mkdocs mkdocs-material

    - name: Install the plugin itself
      run: |
        # Install the plugin from the current directory
        pip install .

    - name: Build documentation
      run: |
        mkdocs build -f docs/mkdocs.yml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
